"""Add google_id with unique constraint

Revision ID: 513e43314fca
Revises: bfa657f4de62
Create Date: 2024-09-16 17:11:32.547751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513e43314fca'
down_revision = 'bfa657f4de62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('uq_google_id', ['google_id'])
        batch_op.create_unique_constraint('uq_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
